In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [58]:
df = pd.read_csv("./kc_house_data.csv")
n = len(df)


inputs = df.drop(["id","date","zipcode","lat","long","sqft_living15","sqft_lot15"], axis = 1)
targets = inputs[["price","grade"]]
inputs = inputs.drop(["price","grade"],axis= 1)

org_mean, org_std = targets.mean(), targets.std()

targets = targets - targets.mean()
targets = targets/targets.std()

targets.describe()

price         grade
count  2.161300e+04  2.161300e+04
mean  -3.419074e-17  1.788439e-16
std    1.000000e+00  1.000000e+00
min   -1.266831e+00 -5.663213e+00
25%   -5.941759e-01 -5.588228e-01
50%   -2.453867e-01 -5.588228e-01
75%    2.857643e-01  2.919089e-01
max    1.950254e+01  4.545567e+00

In [83]:
inputs

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0   
1             3       2.25         2570      7242     2.0           0     0   
2             2       1.00          770     10000     1.0           0     0   
3             4       3.00         1960      5000     1.0           0     0   
4             3       2.00         1680      8080     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
21608         3       2.50         1530      1131     3.0           0     0   
21609         4       2.50         2310      5813     2.0           0     0   
21610         2       0.75         1020      1350     2.0           0     0   
21611         3       2.50         1600      2388     2.0           0     0   
21612         2       0.75         1020      1076     2.0           0     0   

       condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0              3        1180              0      1955             0  
1              3        2170            400      1951          1991  
2              3         770              0      1933             0  
3              5        1050            910      1965             0  
4              3        1680              0      1987             0  
...          ...         ...            ...       ...           ...  
21608          3        1530              0      2009             0  
21609          3        2310              0      2014             0  
21610          3        1020              0      2009             0  
21611          3        1600              0      2004             0  
21612          3        1020              0      2008             0  

[21613 rows x 12 columns]

In [41]:
x = df[["sqft_living","sqft_lot"]]

df[["sqft_living","sqft_lot"]] = (x - x.mean())/x.std()

In [42]:
weights = np.random.normal(size= (2,12))
bias = np.random.normal(size= (1,2))

weights, bias

(array([[-0.51185609,  0.80708424, -1.35968991,  0.24218136,  1.41858455,
         -0.88940556,  0.07235937,  0.26260845,  1.59832187,  1.28536716,
          0.23251452, -0.54048444],
        [-0.67853869, -0.592315  ,  1.24572789,  1.39933659, -0.90939679,
         -0.24746915,  1.27026634,  0.98147171,  0.53504453, -1.02053384,
         -1.49963495, -0.72712989]]),
 array([[0.04092295, 0.40576686]]))

In [59]:

def predict(df, weights, bias):
    pred = np.dot(df, weights.T) + bias

    predictions_df = pd.DataFrame(predictions, columns=["price", "grade"])

    return predictions_df


def mean_squared_error(predictions_df, targets):
    se_df = (predictions_df - targets)**2

    mse = se_df.mean()
    
    return mse

In [82]:
def w_gradient(inputs, targets, predictions):
    grads = np.zeros((2,12))
    
    
    for i,y in enumerate(targets.columns):
        for j,X in enumerate(inputs.columns):
        
            grad = (-2*( (targets - predictions)[y] )*inputs[X]).mean()
            grads[i,j] = grad
            
    return grads

w_grad = w_gradient(inputs, targets, predictions)


def b_gradient():
    grad = np.zeros((1,2))
    
    
    
    return grad

array([[-5.94954659e+01, -4.36131586e+02, -1.16800634e+06,
        -6.53062001e+06,  3.65566724e+02, -2.27351132e+01,
        -5.36783185e+02,  9.90933929e+02, -4.31368706e+05,
        -7.36637632e+05,  6.13947813e+05, -2.16512294e+05],
       [-4.15250415e+04, -2.67553683e+04, -2.71214064e+07,
        -2.01515624e+08, -1.86279135e+04, -1.01485787e+02,
        -3.11925223e+03, -4.04511492e+04, -2.36663374e+07,
        -3.45506900e+06, -2.35742232e+07, -6.82839274e+05]])

In [ ]:
for i in range(100):
    
    
    # make a prediction
    
    # calculate and print the loss
    
    # calculate gradients
    
    # update weights and biases using the gradients
    
    
# output the least loss u could get, tweak the learning rate if u want  