In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [58]:
df = pd.read_csv("./kc_house_data.csv")
n = len(df)


inputs = df.drop(["id","date","zipcode","lat","long","sqft_living15","sqft_lot15"], axis = 1)
targets = inputs[["price","grade"]]
inputs = inputs.drop(["price","grade"],axis= 1)

org_mean, org_std = targets.mean(), targets.std()

targets = targets - targets.mean()
targets = targets/targets.std()

targets.describe()

price         grade
count  2.161300e+04  2.161300e+04
mean  -3.419074e-17  1.788439e-16
std    1.000000e+00  1.000000e+00
min   -1.266831e+00 -5.663213e+00
25%   -5.941759e-01 -5.588228e-01
50%   -2.453867e-01 -5.588228e-01
75%    2.857643e-01  2.919089e-01
max    1.950254e+01  4.545567e+00

In [41]:
x = df[["sqft_living","sqft_lot"]]

df[["sqft_living","sqft_lot"]] = (x - x.mean())/x.std()

In [42]:
weights = np.random.normal(size= (2,12))
bias = np.random.normal(size= (1,2))

weights, bias

(array([[-0.51185609,  0.80708424, -1.35968991,  0.24218136,  1.41858455,
         -0.88940556,  0.07235937,  0.26260845,  1.59832187,  1.28536716,
          0.23251452, -0.54048444],
        [-0.67853869, -0.592315  ,  1.24572789,  1.39933659, -0.90939679,
         -0.24746915,  1.27026634,  0.98147171,  0.53504453, -1.02053384,
         -1.49963495, -0.72712989]]),
 array([[0.04092295, 0.40576686]]))

In [59]:

def predict(df, weights, bias):
    pred = np.dot(df, weights.T) + bias

    predictions_df = pd.DataFrame(predictions, columns=["price", "grade"])

    return predictions_df


def mean_squared_error(predictions_df, targets):
    se_df = (predictions_df - targets)**2

    mse = se_df.mean()
    
    return mse

In [82]:
def w_gradient(inputs, targets, predictions):
    grads = np.zeros((2,12))
    
    
    for i,y in enumerate(targets.columns):
        for j,X in enumerate(inputs.columns):
        
            grad = (-2*( (targets - predictions)[y] )*inputs[X]).mean()
            grads[i,j] = grad
            
    return grads

w_gradient(inputs, targets, predictions)


def b_gradient():
    grad = np.zeros((1,2))
    
    
    
    return grad

array([[-5.94954659e+01, -4.36131586e+02, -1.16800634e+06,
        -6.53062001e+06,  3.65566724e+02, -2.27351132e+01,
        -5.36783185e+02,  9.90933929e+02, -4.31368706e+05,
        -7.36637632e+05,  6.13947813e+05, -2.16512294e+05],
       [-4.15250415e+04, -2.67553683e+04, -2.71214064e+07,
        -2.01515624e+08, -1.86279135e+04, -1.01485787e+02,
        -3.11925223e+03, -4.04511492e+04, -2.36663374e+07,
        -3.45506900e+06, -2.35742232e+07, -6.82839274e+05]])

0       -1290.926326
1        3163.401617
2       -1591.114398
3        1632.127278
4       -1860.179291
            ...     
21608   -2696.186740
21609   -1158.114657
21610   -1109.926352
21611   -2538.532225
21612   -1109.235967
Length: 21613, dtype: float64